module.exports = {
  event: {
    resource: "/guests",
    path: "/guests",
    httpMethod: "GET",
    headers: {
      accept: "application/json, text/plain, */*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "content-type": "application/json",
      Host: "7pd3mzzqxk.execute-api.us-east-1.amazonaws.com",
      origin: "http://localhost:3000",
      referer: "http://localhost:3000/rsvp",
      "User-Agent":
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0",
      "X-Amzn-Trace-Id": "Root=1-6039e1d9-1ea6216800ee4558282dcd1a",
      "x-api-key": "test123",
      "X-Forwarded-For": "73.75.240.178",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https",
    },
    multiValueHeaders: {
      accept: ["application/json, text/plain, */*"],
      "accept-encoding": ["gzip, deflate, br"],
      "accept-language": ["en-US,en;q=0.5"],
      "content-type": ["application/json"],
      Host: ["7pd3mzzqxk.execute-api.us-east-1.amazonaws.com"],
      origin: ["http://localhost:3000"],
      referer: ["http://localhost:3000/rsvp"],
      "User-Agent": [
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0",
      ],
      "X-Amzn-Trace-Id": ["Root=1-6039e1d9-1ea6216800ee4558282dcd1a"],
      "x-api-key": ["test123"],
      "X-Forwarded-For": ["73.75.240.178"],
      "X-Forwarded-Port": ["443"],
      "X-Forwarded-Proto": ["https"],
    },
    queryStringParameters: null,
    multiValueQueryStringParameters: null,
    pathParameters: null,
    stageVariables: null,
    requestContext: {
      resourceId: "4zntwm",
      resourcePath: "/guests",
      httpMethod: "GET",
      extendedRequestId: "bZA6EHbUIAMFVLA=",
      requestTime: "27/Feb/2021:06:08:25 +0000",
      path: "/prod/guests",
      accountId: "703719952365",
      protocol: "HTTP/1.1",
      stage: "prod",
      domainPrefix: "7pd3mzzqxk",
      requestTimeEpoch: 1614406105902,
      requestId: "312e4367-4a68-4561-9986-abedac2a860d",
      identity: {
        cognitoIdentityPoolId: null,
        cognitoIdentityId: null,
        apiKey: "test123",
        principalOrgId: null,
        cognitoAuthenticationType: null,
        userArn: null,
        userAgent:
          "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0",
        accountId: null,
        caller: null,
        sourceIp: "73.75.240.178",
        accessKey: null,
        cognitoAuthenticationProvider: null,
        user: null,
      },
      domainName: "7pd3mzzqxk.execute-api.us-east-1.amazonaws.com",
      apiId: "7pd3mzzqxk",
    },
    body: '{"firstName":"bb","lastName":"yo","partySize":2}',
    isBase64Encoded: false,
  },
};
